name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir:
          - 1.13-slim
          # - 1.12-slim   # otp 24
          # - 1.11-slim   # otp 23
          # - 1.10-slim   # otp 22
          # - 1.9-slim    # otp 22
          # - 1.8-otp-22
          # - 1.8-slim    # otp 21
          # - 1.7-slim    # otp 21
    container:
      image: elixir:${{ matrix.elixir }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      env:
        MIX_ENV: test
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test --trace

  format:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9-slim
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Check Format
      run: mix format --check-formatted --dry-run
